version: '3'
services:
  tango:
    image: tango
    volumes:
      - ./configs/tango/id_rsa:/opt/TangoService/Tango/vmms/id_rsa
      - ./configs/tango/config.py:/opt/TangoService/Tango/config.py
      - ./data/tango/courselabs:/opt/TangoService/Tango/courselabs
  db:
    image: mysql:5.7.27
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./configs/mysql:/etc/mysql/conf.d
      - ./data/db:/var/lib/mysql
  autolab:
    build: ./configs/autolab
    ports:
      - '8080:80'
    volumes:
      - ./data/autolab/courses:/home/app/webapp/courses
      - ./data/autolab/courseConfig:/home/app/webapp/courseConfig
      - ./data/autolab/assessmentConfig:/home/app/webapp/assessmentConfig
